-- ============================================================
-- 01_CREATE_TABLES.sql
-- Tao cau truc database chi tiet theo ERD he thong tu thien.
-- ============================================================

CREATE TABLE TAI_KHOAN (
    MA_TAI_KHOAN      VARCHAR2(20) PRIMARY KEY,
    TEN_DANG_NHAP    VARCHAR2(40) NOT NULL,
    MAT_KHAU          VARCHAR2(100) NOT NULL,
    VAI_TRO           VARCHAR2(20) NOT NULL,
    TRANG_THAI        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    NGAY_TAO          DATE DEFAULT SYSDATE NOT NULL,
    HO_TEN_HIEN_THI   NVARCHAR2(120) NOT NULL,
    EMAIL             VARCHAR2(120),
    SO_DIEN_THOAI     VARCHAR2(20),
    MA_LIEN_KET       VARCHAR2(30),
    CONSTRAINT UK_TAI_KHOAN_USERNAME UNIQUE (TEN_DANG_NHAP),
    CONSTRAINT CK_TAI_KHOAN_VAI_TRO CHECK (VAI_TRO IN ('ADMIN', 'VOLUNTEER', 'SPONSOR')),
    CONSTRAINT CK_TAI_KHOAN_TRANG_THAI CHECK (TRANG_THAI IN ('ACTIVE', 'LOCKED', 'INACTIVE')),
    CONSTRAINT CK_TAI_KHOAN_PHONE CHECK (SO_DIEN_THOAI IS NULL OR (SUBSTR(SO_DIEN_THOAI, 1, 2) = '09' AND LENGTH(SO_DIEN_THOAI) = 10)),
    CONSTRAINT CK_TAI_KHOAN_EMAIL CHECK (EMAIL IS NULL OR LOWER(EMAIL) LIKE '%@gmail.com')
);

CREATE TABLE HO_SO_SINH_VIEN (
    MA_HO_SO          VARCHAR2(20) PRIMARY KEY,
    MA_TAI_KHOAN      VARCHAR2(20) NOT NULL,
    HO_TEN            NVARCHAR2(120) NOT NULL,
    MSSV              VARCHAR2(20) NOT NULL,
    SO_DIEN_THOAI     VARCHAR2(20) NOT NULL,
    EMAIL             VARCHAR2(120),
    KHOA              NVARCHAR2(160) NOT NULL,
    TRUONG            VARCHAR2(20) NOT NULL,
    NGAY_TAO          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_HSSV_TAI_KHOAN UNIQUE (MA_TAI_KHOAN),
    CONSTRAINT UK_HSSV_MSSV UNIQUE (MSSV),
    CONSTRAINT FK_HSSV_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE CASCADE,
    CONSTRAINT CK_HSSV_PHONE CHECK (SUBSTR(SO_DIEN_THOAI, 1, 2) = '09' AND LENGTH(SO_DIEN_THOAI) = 10),
    CONSTRAINT CK_HSSV_EMAIL CHECK (EMAIL IS NULL OR LOWER(EMAIL) LIKE '%@gmail.com'),
    CONSTRAINT CK_HSSV_TRUONG CHECK (TRUONG IN ('UIT', 'UEL', 'HCMUS', 'HCMUT', 'HCMIU', 'UHS', 'HCMUSSH'))
);

CREATE TABLE NHAT_KY_HE_THONG (
    MA_NHAT_KY        VARCHAR2(20) PRIMARY KEY,
    MA_TAI_KHOAN      VARCHAR2(20),
    HANH_DONG         NVARCHAR2(200) NOT NULL,
    THOI_GIAN         DATE DEFAULT SYSDATE NOT NULL,
    CHI_TIET          NVARCHAR2(1000),
    CONSTRAINT FK_NKHT_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE SET NULL
);

CREATE TABLE CHIEN_DICH (
    MA_CHIEN_DICH     VARCHAR2(20) PRIMARY KEY,
    TEN_CHIEN_DICH    NVARCHAR2(200) NOT NULL,
    MO_TA             NVARCHAR2(1200),
    DIA_DIEM          NVARCHAR2(160) NOT NULL,
    NGAY_BAT_DAU      DATE NOT NULL,
    NGAY_KET_THUC     DATE NOT NULL,
    MUC_TIEU_TIEN     NUMBER(15, 2) DEFAULT 0 NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ duyệt' NOT NULL,
    MA_NGUOI_TAO      VARCHAR2(20) NOT NULL,
    NGAY_TAO          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CD_NGUOI_TAO FOREIGN KEY (MA_NGUOI_TAO) REFERENCES TAI_KHOAN(MA_TAI_KHOAN),
    CONSTRAINT CK_CD_MUC_TIEU CHECK (MUC_TIEU_TIEN >= 0),
    CONSTRAINT CK_CD_NGAY CHECK (NGAY_KET_THUC >= NGAY_BAT_DAU),
    CONSTRAINT CK_CD_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ duyệt', N'Đang xét', N'Đã duyệt', N'Đang thực hiện', N'Hoàn thành', N'Tạm dừng', N'Từ chối'))
);

CREATE TABLE DUYET_CHIEN_DICH (
    MA_DUYET          VARCHAR2(20) PRIMARY KEY,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    MA_NGUOI_DUYET    VARCHAR2(20) NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ duyệt' NOT NULL,
    NGAY_DUYET        DATE,
    GHI_CHU           NVARCHAR2(400),
    CONSTRAINT FK_DCD_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT FK_DCD_NGUOI_DUYET FOREIGN KEY (MA_NGUOI_DUYET) REFERENCES TAI_KHOAN(MA_TAI_KHOAN),
    CONSTRAINT CK_DCD_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ duyệt', N'Đang xét', N'Đã duyệt', N'Từ chối'))
);

CREATE TABLE TIN_TUC (
    MA_TIN_TUC        VARCHAR2(20) PRIMARY KEY,
    MA_CHIEN_DICH     VARCHAR2(20),
    TIEU_DE           NVARCHAR2(250) NOT NULL,
    NOI_DUNG          NVARCHAR2(2000) NOT NULL,
    HINH_ANH          VARCHAR2(300),
    NGAY_DANG         DATE DEFAULT SYSDATE NOT NULL,
    MA_TAC_GIA        VARCHAR2(20) NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Nháp' NOT NULL,
    CONSTRAINT FK_TT_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE SET NULL,
    CONSTRAINT FK_TT_TAC_GIA FOREIGN KEY (MA_TAC_GIA) REFERENCES TAI_KHOAN(MA_TAI_KHOAN),
    CONSTRAINT CK_TT_TRANG_THAI CHECK (TRANG_THAI IN (N'Nháp', N'Chờ duyệt', N'Đã đăng', N'Ẩn'))
);

CREATE TABLE BINH_LUAN (
    MA_BINH_LUAN      VARCHAR2(20) PRIMARY KEY,
    MA_TIN_TUC        VARCHAR2(20) NOT NULL,
    MA_TAI_KHOAN      VARCHAR2(20) NOT NULL,
    NOI_DUNG          NVARCHAR2(1000) NOT NULL,
    THOI_GIAN         DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Hiển thị' NOT NULL,
    CONSTRAINT FK_BL_TIN_TUC FOREIGN KEY (MA_TIN_TUC) REFERENCES TIN_TUC(MA_TIN_TUC) ON DELETE CASCADE,
    CONSTRAINT FK_BL_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN),
    CONSTRAINT CK_BL_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ duyệt', N'Hiển thị', N'Ẩn'))
);

CREATE TABLE THAM_GIA_TNV (
    MA_THAM_GIA       VARCHAR2(20) PRIMARY KEY,
    MA_TAI_KHOAN      VARCHAR2(20) NOT NULL,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    NGAY_DANG_KY      DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI_DUYET  NVARCHAR2(50) DEFAULT N'Chờ duyệt' NOT NULL,
    DIEM_DANH_GIA     NUMBER(4, 1),
    GHI_CHU           NVARCHAR2(400),
    CONSTRAINT UK_TG_TNV_CAMPAIGN UNIQUE (MA_TAI_KHOAN, MA_CHIEN_DICH),
    CONSTRAINT FK_TG_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE CASCADE,
    CONSTRAINT FK_TG_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT CK_TG_TRANG_THAI CHECK (TRANG_THAI_DUYET IN (N'Chờ duyệt', N'Đang xét', N'Đã duyệt', N'Từ chối')),
    CONSTRAINT CK_TG_DIEM CHECK (DIEM_DANH_GIA IS NULL OR (DIEM_DANH_GIA BETWEEN 0 AND 10))
);

CREATE TABLE CONG_VIEC (
    MA_CONG_VIEC      VARCHAR2(20) PRIMARY KEY,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    TEN_CONG_VIEC     NVARCHAR2(200) NOT NULL,
    MO_TA             NVARCHAR2(1000),
    SO_LUONG_TNV_CAN  NUMBER(5) DEFAULT 1 NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Đang phân công' NOT NULL,
    NGAY_TAO          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CV_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT CK_CV_SO_LUONG CHECK (SO_LUONG_TNV_CAN > 0),
    CONSTRAINT CK_CV_TRANG_THAI CHECK (TRANG_THAI IN (N'Đang phân công', N'Đã phân công', N'Hoàn thành', N'Tạm dừng'))
);

CREATE TABLE PHAN_CONG (
    MA_PHAN_CONG      VARCHAR2(20) PRIMARY KEY,
    MA_THAM_GIA       VARCHAR2(20) NOT NULL,
    MA_CONG_VIEC      VARCHAR2(20) NOT NULL,
    VAI_TRO_CU_THE    NVARCHAR2(120) NOT NULL,
    NGAY_GIAO         DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Đã phân công' NOT NULL,
    CONSTRAINT UK_PC_TG_CV UNIQUE (MA_THAM_GIA, MA_CONG_VIEC),
    CONSTRAINT FK_PC_THAM_GIA FOREIGN KEY (MA_THAM_GIA) REFERENCES THAM_GIA_TNV(MA_THAM_GIA) ON DELETE CASCADE,
    CONSTRAINT FK_PC_CONG_VIEC FOREIGN KEY (MA_CONG_VIEC) REFERENCES CONG_VIEC(MA_CONG_VIEC) ON DELETE CASCADE,
    CONSTRAINT CK_PC_TRANG_THAI CHECK (TRANG_THAI IN (N'Đã phân công', N'Đang thực hiện', N'Hoàn thành', N'Hủy'))
);

CREATE TABLE DIEM_DANH (
    MA_DIEM_DANH      VARCHAR2(20) PRIMARY KEY,
    MA_THAM_GIA       VARCHAR2(20) NOT NULL,
    NGAY_DIEM_DANH    DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ xác nhận' NOT NULL,
    SO_GIO_GHI_NHAN   NUMBER(5, 2) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DD_THAM_GIA FOREIGN KEY (MA_THAM_GIA) REFERENCES THAM_GIA_TNV(MA_THAM_GIA) ON DELETE CASCADE,
    CONSTRAINT CK_DD_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ xác nhận', N'Có mặt', N'Vắng mặt', N'Từ chối')),
    CONSTRAINT CK_DD_SO_GIO CHECK (SO_GIO_GHI_NHAN >= 0)
);

CREATE TABLE MINH_CHUNG_TNV (
    MA_MINH_CHUNG     VARCHAR2(20) PRIMARY KEY,
    MA_THAM_GIA       VARCHAR2(20) NOT NULL,
    HINH_ANH_URL      VARCHAR2(300) NOT NULL,
    LOAI_MINH_CHUNG   NVARCHAR2(100) NOT NULL,
    NGAY_CAP_NHAT     DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ xác nhận' NOT NULL,
    CONSTRAINT FK_MCTNV_THAM_GIA FOREIGN KEY (MA_THAM_GIA) REFERENCES THAM_GIA_TNV(MA_THAM_GIA) ON DELETE CASCADE,
    CONSTRAINT CK_MCTNV_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ xác nhận', N'Đã xác nhận', N'Từ chối'))
);

CREATE TABLE MINH_CHUNG_CHI_TIEU (
    MA_MINH_CHUNG     VARCHAR2(20) PRIMARY KEY,
    HINH_ANH_URL      VARCHAR2(300) NOT NULL,
    LOAI_MINH_CHUNG   NVARCHAR2(100) NOT NULL,
    NGAY_CAP_NHAT     DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE GIAY_CHUNG_NHAN (
    MA_CHUNG_NHAN     VARCHAR2(20) PRIMARY KEY,
    MA_THAM_GIA       VARCHAR2(20) NOT NULL,
    NGAY_CAP          DATE DEFAULT SYSDATE NOT NULL,
    XEP_LOAI          NVARCHAR2(50) NOT NULL,
    CONSTRAINT UK_GCN_THAM_GIA UNIQUE (MA_THAM_GIA),
    CONSTRAINT FK_GCN_THAM_GIA FOREIGN KEY (MA_THAM_GIA) REFERENCES THAM_GIA_TNV(MA_THAM_GIA) ON DELETE CASCADE,
    CONSTRAINT CK_GCN_XEP_LOAI CHECK (XEP_LOAI IN (N'Xuất sắc', N'Tốt', N'Khá', N'Đạt'))
);

CREATE TABLE QUYEN_GOP_TIEN (
    MA_QUYEN_GOP      VARCHAR2(20) PRIMARY KEY,
    MA_TAI_KHOAN      VARCHAR2(20),
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    NGUOI_QUYEN_GOP   NVARCHAR2(160) NOT NULL,
    SO_TIEN           NUMBER(15, 2) NOT NULL,
    NGAY_GIAO_DICH    DATE DEFAULT SYSDATE NOT NULL,
    PHUONG_THUC       NVARCHAR2(50) NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ xác nhận' NOT NULL,
    CONSTRAINT FK_QGT_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE SET NULL,
    CONSTRAINT FK_QGT_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT CK_QGT_SO_TIEN CHECK (SO_TIEN > 0),
    CONSTRAINT CK_QGT_PHUONG_THUC CHECK (PHUONG_THUC IN (N'Tiền mặt', N'Chuyển khoản')),
    CONSTRAINT CK_QGT_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ xác nhận', N'Đã xác nhận', N'Từ chối'))
);

CREATE TABLE THANH_TOAN (
    MA_THANH_TOAN     VARCHAR2(20) PRIMARY KEY,
    MA_QUYEN_GOP      VARCHAR2(20) NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ xác nhận' NOT NULL,
    MA_GIAO_DICH      VARCHAR2(80),
    NGAY_CAP_NHAT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_TT_QUYEN_GOP UNIQUE (MA_QUYEN_GOP),
    CONSTRAINT FK_TT_QUYEN_GOP FOREIGN KEY (MA_QUYEN_GOP) REFERENCES QUYEN_GOP_TIEN(MA_QUYEN_GOP) ON DELETE CASCADE,
    CONSTRAINT CK_THANH_TOAN_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ xác nhận', N'Đã thanh toán', N'Thất bại', N'Hoàn tiền'))
);

CREATE TABLE CHI_TIEU (
    MA_CHI_TIEU       VARCHAR2(20) PRIMARY KEY,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    SO_TIEN_CHI       NUMBER(15, 2) NOT NULL,
    NGAY_CHI          DATE DEFAULT SYSDATE NOT NULL,
    MUC_DICH          NVARCHAR2(300) NOT NULL,
    MA_MINH_CHUNG     VARCHAR2(20),
    MA_NGUOI_DUYET    VARCHAR2(20),
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ duyệt' NOT NULL,
    CONSTRAINT FK_CT_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT FK_CT_MINH_CHUNG FOREIGN KEY (MA_MINH_CHUNG) REFERENCES MINH_CHUNG_CHI_TIEU(MA_MINH_CHUNG) ON DELETE SET NULL,
    CONSTRAINT FK_CT_NGUOI_DUYET FOREIGN KEY (MA_NGUOI_DUYET) REFERENCES TAI_KHOAN(MA_TAI_KHOAN),
    CONSTRAINT CK_CT_SO_TIEN CHECK (SO_TIEN_CHI > 0),
    CONSTRAINT CK_CT_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ duyệt', N'Đã duyệt', N'Từ chối'))
);

CREATE TABLE DOI_TAC (
    MA_DOI_TAC        VARCHAR2(20) PRIMARY KEY,
    TEN_DOI_TAC       NVARCHAR2(160) NOT NULL,
    LINH_VUC          NVARCHAR2(100) NOT NULL,
    SO_DIEN_THOAI     VARCHAR2(20) NOT NULL,
    EMAIL             VARCHAR2(120),
    DIA_CHI           NVARCHAR2(200),
    CONSTRAINT UK_DT_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_DT_PHONE CHECK (SUBSTR(SO_DIEN_THOAI, 1, 2) = '09' AND LENGTH(SO_DIEN_THOAI) = 10),
    CONSTRAINT CK_DT_EMAIL CHECK (EMAIL IS NULL OR LOWER(EMAIL) LIKE '%@gmail.com')
);

CREATE TABLE TAI_TRO (
    MA_TAI_TRO        VARCHAR2(20) PRIMARY KEY,
    MA_DOI_TAC        VARCHAR2(20) NOT NULL,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    GIA_TRI_TAI_TRO   NUMBER(15, 2) DEFAULT 0 NOT NULL,
    NGAY_KY_KET       DATE DEFAULT SYSDATE NOT NULL,
    HINH_THUC         NVARCHAR2(80) DEFAULT N'Tiền mặt' NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Đã xác nhận' NOT NULL,
    CONSTRAINT FK_TTRO_DOI_TAC FOREIGN KEY (MA_DOI_TAC) REFERENCES DOI_TAC(MA_DOI_TAC) ON DELETE CASCADE,
    CONSTRAINT FK_TTRO_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT CK_TTRO_GIA_TRI CHECK (GIA_TRI_TAI_TRO >= 0),
    CONSTRAINT CK_TTRO_HINH_THUC CHECK (HINH_THUC IN (N'Tiền mặt', N'Chuyển khoản', N'Vật phẩm', N'Vật tư', N'Dịch vụ')),
    CONSTRAINT CK_TTRO_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ xác nhận', N'Đã xác nhận', N'Từ chối'))
);

CREATE TABLE LOAI_VAT_PHAM (
    MA_LOAI           VARCHAR2(20) PRIMARY KEY,
    TEN_LOAI          NVARCHAR2(120) NOT NULL,
    DON_VI_TINH       NVARCHAR2(40) NOT NULL,
    SO_LUONG_TON      NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT UK_LVP_TEN UNIQUE (TEN_LOAI),
    CONSTRAINT CK_LVP_TON CHECK (SO_LUONG_TON >= 0)
);

CREATE TABLE PHIEU_QUYEN_GOP_VP (
    MA_PHIEU_QG       VARCHAR2(20) PRIMARY KEY,
    MA_TAI_KHOAN      VARCHAR2(20),
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    NGUOI_QUYEN_GOP   NVARCHAR2(160) NOT NULL,
    NGAY_TIEP_NHAN    DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chờ xác nhận' NOT NULL,
    GHI_CHU           NVARCHAR2(400),
    CONSTRAINT FK_PQGVP_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE SET NULL,
    CONSTRAINT FK_PQGVP_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT CK_PQGVP_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ xác nhận', N'Đã xác nhận', N'Từ chối'))
);

CREATE TABLE CHI_TIET_QUYEN_GOP_VP (
    MA_PHIEU_QG       VARCHAR2(20) NOT NULL,
    MA_LOAI           VARCHAR2(20) NOT NULL,
    SO_LUONG          NUMBER(10) NOT NULL,
    CONSTRAINT PK_CT_QGVP PRIMARY KEY (MA_PHIEU_QG, MA_LOAI),
    CONSTRAINT FK_CTQGVP_PHIEU FOREIGN KEY (MA_PHIEU_QG) REFERENCES PHIEU_QUYEN_GOP_VP(MA_PHIEU_QG) ON DELETE CASCADE,
    CONSTRAINT FK_CTQGVP_LOAI FOREIGN KEY (MA_LOAI) REFERENCES LOAI_VAT_PHAM(MA_LOAI),
    CONSTRAINT CK_CTQGVP_SO_LUONG CHECK (SO_LUONG > 0)
);

CREATE TABLE PHIEU_XUAT_VAT_PHAM (
    MA_PHIEU_XUAT     VARCHAR2(20) PRIMARY KEY,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    NGAY_XUAT         DATE DEFAULT SYSDATE NOT NULL,
    NGUOI_NHAN        NVARCHAR2(160) NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Đã xuất' NOT NULL,
    GHI_CHU           NVARCHAR2(400),
    CONSTRAINT FK_PXVP_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE,
    CONSTRAINT CK_PXVP_TRANG_THAI CHECK (TRANG_THAI IN (N'Chờ duyệt', N'Đã xuất', N'Hủy'))
);

CREATE TABLE CHI_TIET_XUAT_VP (
    MA_PHIEU_XUAT     VARCHAR2(20) NOT NULL,
    MA_LOAI           VARCHAR2(20) NOT NULL,
    SO_LUONG          NUMBER(10) NOT NULL,
    CONSTRAINT PK_CTXVP PRIMARY KEY (MA_PHIEU_XUAT, MA_LOAI),
    CONSTRAINT FK_CTXVP_PHIEU FOREIGN KEY (MA_PHIEU_XUAT) REFERENCES PHIEU_XUAT_VAT_PHAM(MA_PHIEU_XUAT) ON DELETE CASCADE,
    CONSTRAINT FK_CTXVP_LOAI FOREIGN KEY (MA_LOAI) REFERENCES LOAI_VAT_PHAM(MA_LOAI),
    CONSTRAINT CK_CTXVP_SO_LUONG CHECK (SO_LUONG > 0)
);

CREATE TABLE THONG_BAO (
    MA_THONG_BAO      VARCHAR2(20) PRIMARY KEY,
    MA_TAI_KHOAN      VARCHAR2(20) NOT NULL,
    NOI_DUNG          NVARCHAR2(1000) NOT NULL,
    NGAY_GUI          DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(50) DEFAULT N'Chưa đọc' NOT NULL,
    CONSTRAINT FK_TB_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE CASCADE,
    CONSTRAINT CK_TB_TRANG_THAI CHECK (TRANG_THAI IN (N'Chưa đọc', N'Đã đọc', N'Ẩn'))
);

CREATE TABLE THEO_DOI (
    MA_TAI_KHOAN      VARCHAR2(20) NOT NULL,
    MA_CHIEN_DICH     VARCHAR2(20) NOT NULL,
    NGAY_THEO_DOI     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_THEO_DOI PRIMARY KEY (MA_TAI_KHOAN, MA_CHIEN_DICH),
    CONSTRAINT FK_TD_TAI_KHOAN FOREIGN KEY (MA_TAI_KHOAN) REFERENCES TAI_KHOAN(MA_TAI_KHOAN) ON DELETE CASCADE,
    CONSTRAINT FK_TD_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE CASCADE
);

CREATE TABLE THAM_SO (
    MA_THAM_SO        VARCHAR2(20) PRIMARY KEY,
    TEN_THAM_SO       NVARCHAR2(160) NOT NULL,
    GIA_TRI           NVARCHAR2(300) NOT NULL,
    NGAY_CAP_NHAT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_THAM_SO_TEN UNIQUE (TEN_THAM_SO)
);

CREATE TABLE VAN_HANH (
    NHOM_BANG         NVARCHAR2(80) NOT NULL,
    MA_CHINH          VARCHAR2(30) PRIMARY KEY,
    MA_CHIEN_DICH     VARCHAR2(20),
    MA_LIEN_KET       VARCHAR2(30),
    TIEU_DE           NVARCHAR2(200) NOT NULL,
    NOI_DUNG          NVARCHAR2(1000),
    NGAY_TAO          DATE DEFAULT SYSDATE NOT NULL,
    NGAY_XU_LY        DATE,
    TRANG_THAI        NVARCHAR2(80) NOT NULL,
    NGUOI_TAO         VARCHAR2(30),
    NGUOI_XU_LY       VARCHAR2(30),
    GHI_CHU           NVARCHAR2(400),
    CONSTRAINT FK_VH_CHIEN_DICH FOREIGN KEY (MA_CHIEN_DICH) REFERENCES CHIEN_DICH(MA_CHIEN_DICH) ON DELETE SET NULL
);

CREATE TABLE NOI_DUNG (
    NHOM_BANG         VARCHAR2(50) NOT NULL,
    MA_CHINH          VARCHAR2(30) PRIMARY KEY,
    MA_LIEN_KET       VARCHAR2(30),
    TIEU_DE           NVARCHAR2(200) NOT NULL,
    NOI_DUNG          NVARCHAR2(1200),
    NGAY_TAO          DATE DEFAULT SYSDATE NOT NULL,
    TRANG_THAI        NVARCHAR2(80) NOT NULL,
    GHI_CHU           NVARCHAR2(400)
);

CREATE SEQUENCE SEQ_TK START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NK START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CD START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DCD START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BL START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TG START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CV START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PC START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DD START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MC START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GCN START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_QG START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TTOAN START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TTRO START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LVP START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PQG START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PX START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TB START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TS START WITH 100 INCREMENT BY 1;
