-- ============================================================
-- 02_FUNCTIONS.sql
-- Cac function thong ke, kiem tra va tinh toan nghiep vu.
-- ============================================================

CREATE OR REPLACE FUNCTION FN_NEXT_ID(
    P_PREFIX VARCHAR2,
    P_VALUE NUMBER
) RETURN VARCHAR2
IS
BEGIN
    RETURN P_PREFIX || LPAD(P_VALUE, 3, '0');
END;
/

CREATE OR REPLACE FUNCTION FN_TAI_KHOAN_HOP_LE(
    P_TEN_DANG_NHAP VARCHAR2,
    P_MAT_KHAU VARCHAR2
) RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM TAI_KHOAN
    WHERE UPPER(TEN_DANG_NHAP) = UPPER(P_TEN_DANG_NHAP)
      AND MAT_KHAU = P_MAT_KHAU
      AND TRANG_THAI = 'ACTIVE';

    RETURN CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_CHIEN_DICH_TON_TAI(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM CHIEN_DICH
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    RETURN CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_QUYEN_GOP_TIEN(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN), 0)
    INTO V_TOTAL
    FROM QUYEN_GOP_TIEN
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI = N'Đã xác nhận';

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_TAI_TRO(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(GIA_TRI_TAI_TRO), 0)
    INTO V_TOTAL
    FROM TAI_TRO
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI = N'Đã xác nhận';

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_CHI_TIEU(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN_CHI), 0)
    INTO V_TOTAL
    FROM CHI_TIEU
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI = N'Đã duyệt';

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_NGUON_LUC_CHIEN_DICH(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
BEGIN
    RETURN FN_TONG_QUYEN_GOP_TIEN(P_MA_CHIEN_DICH) + FN_TONG_TAI_TRO(P_MA_CHIEN_DICH);
END;
/

CREATE OR REPLACE FUNCTION FN_SO_TNV_CHIEN_DICH(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM THAM_GIA_TNV
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_TNV_DA_DUYET(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM THAM_GIA_TNV
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI_DUYET = N'Đã duyệt';

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_GIO_TNV(
    P_MA_TAI_KHOAN VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(DD.SO_GIO_GHI_NHAN), 0)
    INTO V_TOTAL
    FROM DIEM_DANH DD
    JOIN THAM_GIA_TNV TG ON TG.MA_THAM_GIA = DD.MA_THAM_GIA
    WHERE TG.MA_TAI_KHOAN = P_MA_TAI_KHOAN
      AND DD.TRANG_THAI = N'Có mặt';

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TON_KHO_VAT_PHAM(
    P_MA_LOAI VARCHAR2
) RETURN NUMBER
IS
    V_TON NUMBER;
BEGIN
    SELECT SO_LUONG_TON
    INTO V_TON
    FROM LOAI_VAT_PHAM
    WHERE MA_LOAI = P_MA_LOAI;

    RETURN V_TON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_VAT_PHAM_QUYEN_GOP(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(CT.SO_LUONG), 0)
    INTO V_TOTAL
    FROM PHIEU_QUYEN_GOP_VP P
    JOIN CHI_TIET_QUYEN_GOP_VP CT ON CT.MA_PHIEU_QG = P.MA_PHIEU_QG
    WHERE P.MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND P.TRANG_THAI = N'Đã xác nhận';

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TY_LE_DAT_MUC_TIEU(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_GOAL NUMBER;
BEGIN
    SELECT NVL(MUC_TIEU_TIEN, 0)
    INTO V_GOAL
    FROM CHIEN_DICH
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    IF V_GOAL <= 0 THEN
        RETURN 0;
    END IF;

    RETURN ROUND(FN_TONG_NGUON_LUC_CHIEN_DICH(P_MA_CHIEN_DICH) / V_GOAL * 100, 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_VAN_HANH_CHO_XU_LY
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM (
        SELECT TRANG_THAI FROM DUYET_CHIEN_DICH
        UNION ALL SELECT TRANG_THAI_DUYET AS TRANG_THAI FROM THAM_GIA_TNV
        UNION ALL SELECT TRANG_THAI FROM CONG_VIEC
        UNION ALL SELECT TRANG_THAI FROM DIEM_DANH
        UNION ALL SELECT TRANG_THAI FROM CHI_TIEU
        UNION ALL SELECT TRANG_THAI FROM QUYEN_GOP_TIEN
        UNION ALL SELECT TRANG_THAI FROM PHIEU_QUYEN_GOP_VP
        UNION ALL SELECT TRANG_THAI FROM MINH_CHUNG_TNV
    )
    WHERE TRANG_THAI IN (N'Chờ duyệt', N'Đang xét', N'Đang phân công', N'Chờ xác nhận');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_NOI_DUNG_CAN_DUYET
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM (
        SELECT TRANG_THAI FROM TIN_TUC
        UNION ALL SELECT TRANG_THAI FROM BINH_LUAN
    )
    WHERE TRANG_THAI IN (N'Nháp', N'Chờ duyệt');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_DIEM_DANH_GIA_TNV(
    P_MA_TAI_KHOAN VARCHAR2
) RETURN NUMBER
IS
    V_SCORE NUMBER;
BEGIN
    SELECT ROUND(
        LEAST(10, NVL(AVG(NVL(DIEM_DANH_GIA, 0)), 0) + LEAST(FN_TONG_GIO_TNV(P_MA_TAI_KHOAN) / 20, 2)),
        1
    )
    INTO V_SCORE
    FROM THAM_GIA_TNV
    WHERE MA_TAI_KHOAN = P_MA_TAI_KHOAN;

    RETURN NVL(V_SCORE, 0);
END;
/

CREATE OR REPLACE FUNCTION FN_TRANG_THAI_TONG_HOP_CD(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NVARCHAR2
IS
    V_STATUS NVARCHAR2(50);
    V_PERCENT NUMBER;
BEGIN
    SELECT TRANG_THAI
    INTO V_STATUS
    FROM CHIEN_DICH
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    V_PERCENT := FN_TY_LE_DAT_MUC_TIEU(P_MA_CHIEN_DICH);

    IF V_STATUS = N'Hoàn thành' OR V_PERCENT >= 100 THEN
        RETURN N'Đạt mục tiêu';
    ELSIF V_STATUS = N'Đang thực hiện' THEN
        RETURN N'Đang vận động';
    ELSIF V_STATUS IN (N'Chờ duyệt', N'Đang xét') THEN
        RETURN N'Chờ quản lý xử lý';
    ELSE
        RETURN V_STATUS;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN N'Không tồn tại';
END;
/
