-- ============================================================
-- 03_TRIGGERS.sql
-- Trigger kiem tra rang buoc, tu dong tao ma, nhat ky,
-- thanh toan, thong bao va cap nhat ton kho.
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_TAI_KHOAN_VALIDATE
BEFORE INSERT OR UPDATE ON TAI_KHOAN
FOR EACH ROW
BEGIN
    IF :NEW.MA_TAI_KHOAN IS NULL THEN
        :NEW.MA_TAI_KHOAN := FN_NEXT_ID('TK', SEQ_TK.NEXTVAL);
    END IF;

    :NEW.TEN_DANG_NHAP := UPPER(TRIM(:NEW.TEN_DANG_NHAP));

    IF :NEW.VAI_TRO NOT IN ('ADMIN', 'VOLUNTEER', 'SPONSOR') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Vai tro tai khoan khong hop le.');
    END IF;

    IF :NEW.TRANG_THAI NOT IN ('ACTIVE', 'LOCKED', 'INACTIVE') THEN
        RAISE_APPLICATION_ERROR(-20002, 'Trang thai tai khoan khong hop le.');
    END IF;

    IF :NEW.EMAIL IS NOT NULL AND NOT REGEXP_LIKE(:NEW.EMAIL, '^[A-Za-z0-9._%+-]+@gmail\.com$') THEN
        RAISE_APPLICATION_ERROR(-20003, 'Email tai khoan phai co dang @gmail.com.');
    END IF;

    IF :NEW.SO_DIEN_THOAI IS NOT NULL AND NOT REGEXP_LIKE(:NEW.SO_DIEN_THOAI, '^09[0-9]{8}$') THEN
        RAISE_APPLICATION_ERROR(-20004, 'So dien thoai tai khoan phai co dang 09xxxxxxxx.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TAI_KHOAN_LOG
AFTER INSERT OR UPDATE ON TAI_KHOAN
FOR EACH ROW
DECLARE
    V_HANH_DONG NVARCHAR2(200);
BEGIN
    IF INSERTING THEN
        V_HANH_DONG := N'Tạo tài khoản';
    ELSE
        V_HANH_DONG := N'Cập nhật tài khoản';
    END IF;

    INSERT INTO NHAT_KY_HE_THONG (
        MA_NHAT_KY, MA_TAI_KHOAN, HANH_DONG, THOI_GIAN, CHI_TIET
    ) VALUES (
        FN_NEXT_ID('NK', SEQ_NK.NEXTVAL),
        :NEW.MA_TAI_KHOAN,
        V_HANH_DONG,
        SYSDATE,
        :NEW.TEN_DANG_NHAP || ' - ' || :NEW.VAI_TRO || ' - ' || :NEW.TRANG_THAI
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_HSSV_VALIDATE
BEFORE INSERT OR UPDATE ON HO_SO_SINH_VIEN
FOR EACH ROW
DECLARE
    V_ROLE VARCHAR2(20);
BEGIN
    IF :NEW.MA_HO_SO IS NULL THEN
        :NEW.MA_HO_SO := FN_NEXT_ID('HS', SEQ_HS.NEXTVAL);
    END IF;

    SELECT VAI_TRO
    INTO V_ROLE
    FROM TAI_KHOAN
    WHERE MA_TAI_KHOAN = :NEW.MA_TAI_KHOAN;

    IF V_ROLE != 'VOLUNTEER' THEN
        RAISE_APPLICATION_ERROR(-20005, 'Ho so sinh vien chi duoc lien ket voi tai khoan tinh nguyen vien.');
    END IF;

    IF NOT REGEXP_LIKE(:NEW.SO_DIEN_THOAI, '^09[0-9]{8}$') THEN
        RAISE_APPLICATION_ERROR(-20006, 'So dien thoai sinh vien phai co dang 09xxxxxxxx.');
    END IF;

    IF :NEW.EMAIL IS NOT NULL AND NOT REGEXP_LIKE(:NEW.EMAIL, '^[A-Za-z0-9._%+-]+@gmail\.com$') THEN
        RAISE_APPLICATION_ERROR(-20007, 'Email sinh vien phai co dang @gmail.com.');
    END IF;

    IF :NEW.TRUONG NOT IN ('UIT', 'UEL', 'HCMUS', 'HCMUT', 'HCMIU', 'UHS', 'HCMUSSH') THEN
        RAISE_APPLICATION_ERROR(-20008, 'Truong phai thuoc DHQG-TPHCM.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20009, 'Tai khoan cua ho so sinh vien khong ton tai.');
END;
/

CREATE OR REPLACE TRIGGER TRG_CHIEN_DICH_VALIDATE
BEFORE INSERT OR UPDATE ON CHIEN_DICH
FOR EACH ROW
DECLARE
    V_ROLE VARCHAR2(20);
BEGIN
    IF :NEW.MA_CHIEN_DICH IS NULL THEN
        :NEW.MA_CHIEN_DICH := FN_NEXT_ID('CD', SEQ_CD.NEXTVAL);
    END IF;

    SELECT VAI_TRO
    INTO V_ROLE
    FROM TAI_KHOAN
    WHERE MA_TAI_KHOAN = :NEW.MA_NGUOI_TAO;

    IF V_ROLE != 'ADMIN' THEN
        RAISE_APPLICATION_ERROR(-20010, 'Chi admin moi duoc tao chien dich.');
    END IF;

    IF :NEW.MUC_TIEU_TIEN < 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Muc tieu tien khong duoc am.');
    END IF;

    IF :NEW.NGAY_KET_THUC < :NEW.NGAY_BAT_DAU THEN
        RAISE_APPLICATION_ERROR(-20012, 'Ngay ket thuc phai lon hon hoac bang ngay bat dau.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20013, 'Nguoi tao chien dich khong ton tai.');
END;
/

CREATE OR REPLACE TRIGGER TRG_CHIEN_DICH_TAO_DUYET
AFTER INSERT ON CHIEN_DICH
FOR EACH ROW
BEGIN
    INSERT INTO DUYET_CHIEN_DICH (
        MA_DUYET, MA_CHIEN_DICH, MA_NGUOI_DUYET, TRANG_THAI, NGAY_DUYET, GHI_CHU
    ) VALUES (
        FN_NEXT_ID('DCD', SEQ_DCD.NEXTVAL),
        :NEW.MA_CHIEN_DICH,
        :NEW.MA_NGUOI_TAO,
        CASE
            WHEN :NEW.TRANG_THAI IN (N'Đã duyệt', N'Đang thực hiện', N'Hoàn thành') THEN N'Đã duyệt'
            WHEN :NEW.TRANG_THAI = N'Từ chối' THEN N'Từ chối'
            ELSE N'Chờ duyệt'
        END,
        CASE
            WHEN :NEW.TRANG_THAI IN (N'Đã duyệt', N'Đang thực hiện', N'Hoàn thành', N'Từ chối') THEN SYSDATE
            ELSE NULL
        END,
        N'Tự động tạo phiếu duyệt chiến dịch'
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_DUYET_CHIEN_DICH_SYNC
AFTER UPDATE OF TRANG_THAI ON DUYET_CHIEN_DICH
FOR EACH ROW
BEGIN
    IF :NEW.TRANG_THAI = N'Đã duyệt' THEN
        UPDATE CHIEN_DICH
        SET TRANG_THAI = N'Đã duyệt'
        WHERE MA_CHIEN_DICH = :NEW.MA_CHIEN_DICH;
    ELSIF :NEW.TRANG_THAI = N'Từ chối' THEN
        UPDATE CHIEN_DICH
        SET TRANG_THAI = N'Từ chối'
        WHERE MA_CHIEN_DICH = :NEW.MA_CHIEN_DICH;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_THAM_GIA_VALIDATE
BEFORE INSERT OR UPDATE ON THAM_GIA_TNV
FOR EACH ROW
DECLARE
    V_ROLE VARCHAR2(20);
    V_CAMPAIGN_STATUS NVARCHAR2(50);
BEGIN
    IF :NEW.MA_THAM_GIA IS NULL THEN
        :NEW.MA_THAM_GIA := FN_NEXT_ID('TG', SEQ_TG.NEXTVAL);
    END IF;

    SELECT VAI_TRO
    INTO V_ROLE
    FROM TAI_KHOAN
    WHERE MA_TAI_KHOAN = :NEW.MA_TAI_KHOAN;

    IF V_ROLE != 'VOLUNTEER' THEN
        RAISE_APPLICATION_ERROR(-20014, 'Dang ky tham gia chi danh cho tai khoan tinh nguyen vien.');
    END IF;

    SELECT TRANG_THAI
    INTO V_CAMPAIGN_STATUS
    FROM CHIEN_DICH
    WHERE MA_CHIEN_DICH = :NEW.MA_CHIEN_DICH;

    IF V_CAMPAIGN_STATUS IN (N'Từ chối', N'Tạm dừng') THEN
        RAISE_APPLICATION_ERROR(-20015, 'Khong the dang ky vao chien dich dang tam dung hoac bi tu choi.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20016, 'Tai khoan hoac chien dich dang ky khong ton tai.');
END;
/

CREATE OR REPLACE TRIGGER TRG_THAM_GIA_NOTIFY
AFTER INSERT OR UPDATE OF TRANG_THAI_DUYET ON THAM_GIA_TNV
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO THONG_BAO VALUES (
            FN_NEXT_ID('TB', SEQ_TB.NEXTVAL),
            :NEW.MA_TAI_KHOAN,
            N'Hồ sơ đăng ký chiến dịch ' || :NEW.MA_CHIEN_DICH || N' đã được tiếp nhận.',
            SYSDATE,
            N'Chưa đọc'
        );
    ELSIF NVL(:OLD.TRANG_THAI_DUYET, ' ') != NVL(:NEW.TRANG_THAI_DUYET, ' ') THEN
        INSERT INTO THONG_BAO VALUES (
            FN_NEXT_ID('TB', SEQ_TB.NEXTVAL),
            :NEW.MA_TAI_KHOAN,
            N'Trạng thái đăng ký chiến dịch ' || :NEW.MA_CHIEN_DICH || N': ' || :NEW.TRANG_THAI_DUYET,
            SYSDATE,
            N'Chưa đọc'
        );
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DOI_TAC_VALIDATE
BEFORE INSERT OR UPDATE ON DOI_TAC
FOR EACH ROW
BEGIN
    IF :NEW.MA_DOI_TAC IS NULL THEN
        :NEW.MA_DOI_TAC := FN_NEXT_ID('DT', SEQ_DT.NEXTVAL);
    END IF;

    IF NOT REGEXP_LIKE(:NEW.SO_DIEN_THOAI, '^09[0-9]{8}$') THEN
        RAISE_APPLICATION_ERROR(-20017, 'So dien thoai doi tac phai co dang 09xxxxxxxx.');
    END IF;

    IF :NEW.EMAIL IS NOT NULL AND NOT REGEXP_LIKE(:NEW.EMAIL, '^[A-Za-z0-9._%+-]+@gmail\.com$') THEN
        RAISE_APPLICATION_ERROR(-20018, 'Email doi tac phai co dang @gmail.com.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TAI_TRO_VALIDATE
BEFORE INSERT OR UPDATE ON TAI_TRO
FOR EACH ROW
BEGIN
    IF :NEW.MA_TAI_TRO IS NULL THEN
        :NEW.MA_TAI_TRO := FN_NEXT_ID('TTRO', SEQ_TTRO.NEXTVAL);
    END IF;

    IF :NEW.GIA_TRI_TAI_TRO < 0 THEN
        RAISE_APPLICATION_ERROR(-20019, 'Gia tri tai tro khong duoc am.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_QG_TIEN_VALIDATE
BEFORE INSERT OR UPDATE ON QUYEN_GOP_TIEN
FOR EACH ROW
BEGIN
    IF :NEW.MA_QUYEN_GOP IS NULL THEN
        :NEW.MA_QUYEN_GOP := FN_NEXT_ID('QG', SEQ_QG.NEXTVAL);
    END IF;

    IF :NEW.SO_TIEN <= 0 THEN
        RAISE_APPLICATION_ERROR(-20020, 'Quyen gop bang tien phai lon hon 0.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_QG_TIEN_TAO_THANH_TOAN
AFTER INSERT ON QUYEN_GOP_TIEN
FOR EACH ROW
BEGIN
    INSERT INTO THANH_TOAN VALUES (
        FN_NEXT_ID('TT', SEQ_TTOAN.NEXTVAL),
        :NEW.MA_QUYEN_GOP,
        CASE WHEN :NEW.TRANG_THAI = N'Đã xác nhận' THEN N'Đã thanh toán' ELSE N'Chờ xác nhận' END,
        'GD' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || :NEW.MA_QUYEN_GOP,
        SYSDATE
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_QG_TIEN_SYNC_THANH_TOAN
AFTER UPDATE OF TRANG_THAI ON QUYEN_GOP_TIEN
FOR EACH ROW
BEGIN
    UPDATE THANH_TOAN
    SET TRANG_THAI = CASE
            WHEN :NEW.TRANG_THAI = N'Đã xác nhận' THEN N'Đã thanh toán'
            WHEN :NEW.TRANG_THAI = N'Từ chối' THEN N'Thất bại'
            ELSE N'Chờ xác nhận'
        END,
        NGAY_CAP_NHAT = SYSDATE
    WHERE MA_QUYEN_GOP = :NEW.MA_QUYEN_GOP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CHI_TIEU_VALIDATE
BEFORE INSERT OR UPDATE ON CHI_TIEU
FOR EACH ROW
DECLARE
    V_AVAILABLE NUMBER;
BEGIN
    IF :NEW.MA_CHI_TIEU IS NULL THEN
        :NEW.MA_CHI_TIEU := FN_NEXT_ID('CT', SEQ_CT.NEXTVAL);
    END IF;

    V_AVAILABLE := FN_TONG_NGUON_LUC_CHIEN_DICH(:NEW.MA_CHIEN_DICH) - FN_TONG_CHI_TIEU(:NEW.MA_CHIEN_DICH);

    IF :NEW.SO_TIEN_CHI <= 0 THEN
        RAISE_APPLICATION_ERROR(-20021, 'So tien chi phai lon hon 0.');
    END IF;

    IF INSERTING AND :NEW.SO_TIEN_CHI > V_AVAILABLE THEN
        RAISE_APPLICATION_ERROR(-20022, 'So tien chi vuot qua nguon luc da ghi nhan cua chien dich.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PHIEU_QG_VP_VALIDATE
BEFORE INSERT OR UPDATE ON PHIEU_QUYEN_GOP_VP
FOR EACH ROW
BEGIN
    IF :NEW.MA_PHIEU_QG IS NULL THEN
        :NEW.MA_PHIEU_QG := FN_NEXT_ID('PQG', SEQ_PQG.NEXTVAL);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CT_QG_VP_CAP_NHAT_TON
AFTER INSERT ON CHI_TIET_QUYEN_GOP_VP
FOR EACH ROW
DECLARE
    V_STATUS NVARCHAR2(50);
BEGIN
    SELECT TRANG_THAI
    INTO V_STATUS
    FROM PHIEU_QUYEN_GOP_VP
    WHERE MA_PHIEU_QG = :NEW.MA_PHIEU_QG;

    IF V_STATUS = N'Đã xác nhận' THEN
        UPDATE LOAI_VAT_PHAM
        SET SO_LUONG_TON = SO_LUONG_TON + :NEW.SO_LUONG
        WHERE MA_LOAI = :NEW.MA_LOAI;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PHIEU_XUAT_VALIDATE
BEFORE INSERT OR UPDATE ON PHIEU_XUAT_VAT_PHAM
FOR EACH ROW
BEGIN
    IF :NEW.MA_PHIEU_XUAT IS NULL THEN
        :NEW.MA_PHIEU_XUAT := FN_NEXT_ID('PX', SEQ_PX.NEXTVAL);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CT_XUAT_KIEM_TRA_TON
BEFORE INSERT ON CHI_TIET_XUAT_VP
FOR EACH ROW
DECLARE
    V_TON NUMBER;
BEGIN
    SELECT SO_LUONG_TON
    INTO V_TON
    FROM LOAI_VAT_PHAM
    WHERE MA_LOAI = :NEW.MA_LOAI;

    IF V_TON < :NEW.SO_LUONG THEN
        RAISE_APPLICATION_ERROR(-20023, 'So luong xuat vuot qua ton kho vat pham.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CT_XUAT_TRU_TON
AFTER INSERT ON CHI_TIET_XUAT_VP
FOR EACH ROW
BEGIN
    UPDATE LOAI_VAT_PHAM
    SET SO_LUONG_TON = SO_LUONG_TON - :NEW.SO_LUONG
    WHERE MA_LOAI = :NEW.MA_LOAI;
END;
/

CREATE OR REPLACE TRIGGER TRG_NOI_DUNG_VALIDATE
BEFORE INSERT OR UPDATE ON TIN_TUC
FOR EACH ROW
BEGIN
    IF :NEW.MA_TIN_TUC IS NULL THEN
        :NEW.MA_TIN_TUC := FN_NEXT_ID('TT', SEQ_TT.NEXTVAL);
    END IF;
END;
/
