-- ============================================================
-- 04_PROCEDURES.sql
-- Stored procedure gom cac giao tac nghiep vu chinh.
-- Moi procedure dung SAVEPOINT va tra loi bang loi ro rang.
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_TAO_TAI_KHOAN (
    P_TEN_DANG_NHAP VARCHAR2,
    P_MAT_KHAU VARCHAR2,
    P_VAI_TRO VARCHAR2,
    P_HO_TEN_HIEN_THI NVARCHAR2,
    P_EMAIL VARCHAR2,
    P_SO_DIEN_THOAI VARCHAR2
)
IS
    V_MA_TAI_KHOAN VARCHAR2(20);
BEGIN
    SAVEPOINT SP_TAO_TAI_KHOAN_START;

    V_MA_TAI_KHOAN := FN_NEXT_ID('TK', SEQ_TK.NEXTVAL);

    INSERT INTO TAI_KHOAN (
        MA_TAI_KHOAN, TEN_DANG_NHAP, MAT_KHAU, VAI_TRO, TRANG_THAI,
        NGAY_TAO, HO_TEN_HIEN_THI, EMAIL, SO_DIEN_THOAI, MA_LIEN_KET
    ) VALUES (
        V_MA_TAI_KHOAN, P_TEN_DANG_NHAP, P_MAT_KHAU, P_VAI_TRO, 'ACTIVE',
        SYSDATE, P_HO_TEN_HIEN_THI, P_EMAIL, P_SO_DIEN_THOAI, NULL
    );
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK TO SP_TAO_TAI_KHOAN_START;
        RAISE_APPLICATION_ERROR(-20101, 'Ten dang nhap hoac email da ton tai.');
    WHEN OTHERS THEN
        ROLLBACK TO SP_TAO_TAI_KHOAN_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_TAO_CHIEN_DICH (
    P_TEN_CHIEN_DICH NVARCHAR2,
    P_MO_TA NVARCHAR2,
    P_DIA_DIEM NVARCHAR2,
    P_NGAY_BAT_DAU DATE,
    P_NGAY_KET_THUC DATE,
    P_MUC_TIEU_TIEN NUMBER,
    P_MA_NGUOI_TAO VARCHAR2
)
IS
    V_MA_CHIEN_DICH VARCHAR2(20);
BEGIN
    SAVEPOINT SP_TAO_CHIEN_DICH_START;

    V_MA_CHIEN_DICH := FN_NEXT_ID('CD', SEQ_CD.NEXTVAL);

    INSERT INTO CHIEN_DICH (
        MA_CHIEN_DICH, TEN_CHIEN_DICH, MO_TA, DIA_DIEM, NGAY_BAT_DAU,
        NGAY_KET_THUC, MUC_TIEU_TIEN, TRANG_THAI, MA_NGUOI_TAO, NGAY_TAO
    ) VALUES (
        V_MA_CHIEN_DICH, P_TEN_CHIEN_DICH, P_MO_TA, P_DIA_DIEM, P_NGAY_BAT_DAU,
        P_NGAY_KET_THUC, P_MUC_TIEU_TIEN, N'Chờ duyệt', P_MA_NGUOI_TAO, SYSDATE
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_TAO_CHIEN_DICH_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_DUYET_CHIEN_DICH (
    P_MA_CHIEN_DICH VARCHAR2,
    P_MA_NGUOI_DUYET VARCHAR2,
    P_TRANG_THAI NVARCHAR2,
    P_GHI_CHU NVARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    SAVEPOINT SP_DUYET_CHIEN_DICH_START;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM DUYET_CHIEN_DICH
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    IF V_COUNT = 0 THEN
        INSERT INTO DUYET_CHIEN_DICH VALUES (
            FN_NEXT_ID('DCD', SEQ_DCD.NEXTVAL),
            P_MA_CHIEN_DICH,
            P_MA_NGUOI_DUYET,
            P_TRANG_THAI,
            SYSDATE,
            P_GHI_CHU
        );
    ELSE
        UPDATE DUYET_CHIEN_DICH
        SET MA_NGUOI_DUYET = P_MA_NGUOI_DUYET,
            TRANG_THAI = P_TRANG_THAI,
            NGAY_DUYET = SYSDATE,
            GHI_CHU = P_GHI_CHU
        WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_DUYET_CHIEN_DICH_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_DANG_KY_TNV (
    P_MA_TAI_KHOAN VARCHAR2,
    P_MA_CHIEN_DICH VARCHAR2,
    P_GHI_CHU NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_DANG_KY_TNV_START;

    INSERT INTO THAM_GIA_TNV (
        MA_THAM_GIA, MA_TAI_KHOAN, MA_CHIEN_DICH, NGAY_DANG_KY,
        TRANG_THAI_DUYET, DIEM_DANH_GIA, GHI_CHU
    ) VALUES (
        FN_NEXT_ID('TG', SEQ_TG.NEXTVAL), P_MA_TAI_KHOAN, P_MA_CHIEN_DICH,
        SYSDATE, N'Chờ duyệt', NULL, P_GHI_CHU
    );
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK TO SP_DANG_KY_TNV_START;
        RAISE_APPLICATION_ERROR(-20102, 'Tinh nguyen vien da dang ky chien dich nay.');
    WHEN OTHERS THEN
        ROLLBACK TO SP_DANG_KY_TNV_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_DUYET_TNV (
    P_MA_THAM_GIA VARCHAR2,
    P_TRANG_THAI NVARCHAR2,
    P_DIEM_DANH_GIA NUMBER,
    P_GHI_CHU NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_DUYET_TNV_START;

    UPDATE THAM_GIA_TNV
    SET TRANG_THAI_DUYET = P_TRANG_THAI,
        DIEM_DANH_GIA = P_DIEM_DANH_GIA,
        GHI_CHU = P_GHI_CHU
    WHERE MA_THAM_GIA = P_MA_THAM_GIA;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20103, 'Khong tim thay ho so tham gia TNV.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_DUYET_TNV_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_TAO_CONG_VIEC (
    P_MA_CHIEN_DICH VARCHAR2,
    P_TEN_CONG_VIEC NVARCHAR2,
    P_MO_TA NVARCHAR2,
    P_SO_LUONG_TNV_CAN NUMBER
)
IS
BEGIN
    SAVEPOINT SP_TAO_CONG_VIEC_START;

    INSERT INTO CONG_VIEC VALUES (
        FN_NEXT_ID('CV', SEQ_CV.NEXTVAL),
        P_MA_CHIEN_DICH,
        P_TEN_CONG_VIEC,
        P_MO_TA,
        P_SO_LUONG_TNV_CAN,
        N'Đang phân công',
        SYSDATE
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_TAO_CONG_VIEC_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_PHAN_CONG_TNV (
    P_MA_THAM_GIA VARCHAR2,
    P_MA_CONG_VIEC VARCHAR2,
    P_VAI_TRO_CU_THE NVARCHAR2
)
IS
    V_STATUS NVARCHAR2(50);
BEGIN
    SAVEPOINT SP_PHAN_CONG_TNV_START;

    SELECT TRANG_THAI_DUYET
    INTO V_STATUS
    FROM THAM_GIA_TNV
    WHERE MA_THAM_GIA = P_MA_THAM_GIA;

    IF V_STATUS != N'Đã duyệt' THEN
        RAISE_APPLICATION_ERROR(-20104, 'Chi phan cong TNV da duoc duyet.');
    END IF;

    INSERT INTO PHAN_CONG VALUES (
        FN_NEXT_ID('PC', SEQ_PC.NEXTVAL),
        P_MA_THAM_GIA,
        P_MA_CONG_VIEC,
        P_VAI_TRO_CU_THE,
        SYSDATE,
        N'Đã phân công'
    );

    UPDATE CONG_VIEC
    SET TRANG_THAI = N'Đã phân công'
    WHERE MA_CONG_VIEC = P_MA_CONG_VIEC;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK TO SP_PHAN_CONG_TNV_START;
        RAISE_APPLICATION_ERROR(-20105, 'TNV da duoc phan cong vao cong viec nay.');
    WHEN NO_DATA_FOUND THEN
        ROLLBACK TO SP_PHAN_CONG_TNV_START;
        RAISE_APPLICATION_ERROR(-20106, 'Ho so tham gia khong ton tai.');
    WHEN OTHERS THEN
        ROLLBACK TO SP_PHAN_CONG_TNV_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_DIEM_DANH_TNV (
    P_MA_THAM_GIA VARCHAR2,
    P_TRANG_THAI NVARCHAR2,
    P_SO_GIO_GHI_NHAN NUMBER
)
IS
BEGIN
    SAVEPOINT SP_DIEM_DANH_TNV_START;

    INSERT INTO DIEM_DANH VALUES (
        FN_NEXT_ID('DD', SEQ_DD.NEXTVAL),
        P_MA_THAM_GIA,
        SYSDATE,
        P_TRANG_THAI,
        P_SO_GIO_GHI_NHAN
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_DIEM_DANH_TNV_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_GHI_NHAN_TAI_TRO (
    P_MA_DOI_TAC VARCHAR2,
    P_MA_CHIEN_DICH VARCHAR2,
    P_GIA_TRI_TAI_TRO NUMBER,
    P_HINH_THUC NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_GHI_NHAN_TAI_TRO_START;

    INSERT INTO TAI_TRO VALUES (
        FN_NEXT_ID('TTRO', SEQ_TTRO.NEXTVAL),
        P_MA_DOI_TAC,
        P_MA_CHIEN_DICH,
        P_GIA_TRI_TAI_TRO,
        SYSDATE,
        P_HINH_THUC,
        N'Đã xác nhận'
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_GHI_NHAN_TAI_TRO_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_GHI_NHAN_QUYEN_GOP_TIEN (
    P_MA_TAI_KHOAN VARCHAR2,
    P_MA_CHIEN_DICH VARCHAR2,
    P_NGUOI_QUYEN_GOP NVARCHAR2,
    P_SO_TIEN NUMBER,
    P_PHUONG_THUC NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_GHI_NHAN_QG_TIEN_START;

    INSERT INTO QUYEN_GOP_TIEN VALUES (
        FN_NEXT_ID('QG', SEQ_QG.NEXTVAL),
        P_MA_TAI_KHOAN,
        P_MA_CHIEN_DICH,
        P_NGUOI_QUYEN_GOP,
        P_SO_TIEN,
        SYSDATE,
        P_PHUONG_THUC,
        N'Chờ xác nhận'
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_GHI_NHAN_QG_TIEN_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_TIEP_NHAN_VAT_PHAM (
    P_MA_TAI_KHOAN VARCHAR2,
    P_MA_CHIEN_DICH VARCHAR2,
    P_NGUOI_QUYEN_GOP NVARCHAR2,
    P_MA_LOAI VARCHAR2,
    P_SO_LUONG NUMBER,
    P_GHI_CHU NVARCHAR2
)
IS
    V_MA_PHIEU VARCHAR2(20);
BEGIN
    SAVEPOINT SP_TIEP_NHAN_VAT_PHAM_START;

    V_MA_PHIEU := FN_NEXT_ID('PQG', SEQ_PQG.NEXTVAL);

    INSERT INTO PHIEU_QUYEN_GOP_VP VALUES (
        V_MA_PHIEU,
        P_MA_TAI_KHOAN,
        P_MA_CHIEN_DICH,
        P_NGUOI_QUYEN_GOP,
        SYSDATE,
        N'Đã xác nhận',
        P_GHI_CHU
    );

    INSERT INTO CHI_TIET_QUYEN_GOP_VP VALUES (
        V_MA_PHIEU,
        P_MA_LOAI,
        P_SO_LUONG
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_TIEP_NHAN_VAT_PHAM_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_XUAT_VAT_PHAM (
    P_MA_CHIEN_DICH VARCHAR2,
    P_NGUOI_NHAN NVARCHAR2,
    P_MA_LOAI VARCHAR2,
    P_SO_LUONG NUMBER,
    P_GHI_CHU NVARCHAR2
)
IS
    V_MA_PHIEU_XUAT VARCHAR2(20);
BEGIN
    SAVEPOINT SP_XUAT_VAT_PHAM_START;

    V_MA_PHIEU_XUAT := FN_NEXT_ID('PX', SEQ_PX.NEXTVAL);

    INSERT INTO PHIEU_XUAT_VAT_PHAM VALUES (
        V_MA_PHIEU_XUAT,
        P_MA_CHIEN_DICH,
        SYSDATE,
        P_NGUOI_NHAN,
        N'Đã xuất',
        P_GHI_CHU
    );

    INSERT INTO CHI_TIET_XUAT_VP VALUES (
        V_MA_PHIEU_XUAT,
        P_MA_LOAI,
        P_SO_LUONG
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_XUAT_VAT_PHAM_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_GHI_NHAN_CHI_TIEU (
    P_MA_CHIEN_DICH VARCHAR2,
    P_SO_TIEN_CHI NUMBER,
    P_MUC_DICH NVARCHAR2,
    P_HINH_ANH_URL VARCHAR2,
    P_LOAI_MINH_CHUNG NVARCHAR2
)
IS
    V_MA_MINH_CHUNG VARCHAR2(20);
BEGIN
    SAVEPOINT SP_GHI_NHAN_CHI_TIEU_START;

    V_MA_MINH_CHUNG := FN_NEXT_ID('MC', SEQ_MC.NEXTVAL);

    INSERT INTO MINH_CHUNG_CHI_TIEU VALUES (
        V_MA_MINH_CHUNG,
        P_HINH_ANH_URL,
        P_LOAI_MINH_CHUNG,
        SYSDATE
    );

    INSERT INTO CHI_TIEU VALUES (
        FN_NEXT_ID('CT', SEQ_CT.NEXTVAL),
        P_MA_CHIEN_DICH,
        P_SO_TIEN_CHI,
        SYSDATE,
        P_MUC_DICH,
        V_MA_MINH_CHUNG,
        NULL,
        N'Chờ duyệt'
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_GHI_NHAN_CHI_TIEU_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_DUYET_CHI_TIEU (
    P_MA_CHI_TIEU VARCHAR2,
    P_MA_NGUOI_DUYET VARCHAR2,
    P_TRANG_THAI NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_DUYET_CHI_TIEU_START;

    UPDATE CHI_TIEU
    SET MA_NGUOI_DUYET = P_MA_NGUOI_DUYET,
        TRANG_THAI = P_TRANG_THAI
    WHERE MA_CHI_TIEU = P_MA_CHI_TIEU;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20107, 'Khong tim thay khoan chi tieu.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_DUYET_CHI_TIEU_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_TAO_TIN_TUC (
    P_MA_CHIEN_DICH VARCHAR2,
    P_TIEU_DE NVARCHAR2,
    P_NOI_DUNG NVARCHAR2,
    P_HINH_ANH VARCHAR2,
    P_MA_TAC_GIA VARCHAR2,
    P_TRANG_THAI NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_TAO_TIN_TUC_START;

    INSERT INTO TIN_TUC VALUES (
        FN_NEXT_ID('TT', SEQ_TT.NEXTVAL),
        P_MA_CHIEN_DICH,
        P_TIEU_DE,
        P_NOI_DUNG,
        P_HINH_ANH,
        SYSDATE,
        P_MA_TAC_GIA,
        P_TRANG_THAI
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_TAO_TIN_TUC_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_GUI_THONG_BAO (
    P_MA_TAI_KHOAN VARCHAR2,
    P_NOI_DUNG NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_GUI_THONG_BAO_START;

    INSERT INTO THONG_BAO VALUES (
        FN_NEXT_ID('TB', SEQ_TB.NEXTVAL),
        P_MA_TAI_KHOAN,
        P_NOI_DUNG,
        SYSDATE,
        N'Chưa đọc'
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_GUI_THONG_BAO_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_KHOA_TAI_KHOAN (
    P_MA_TAI_KHOAN VARCHAR2,
    P_NGUOI_THUC_HIEN VARCHAR2,
    P_LY_DO NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_KHOA_TAI_KHOAN_START;

    UPDATE TAI_KHOAN
    SET TRANG_THAI = 'LOCKED'
    WHERE MA_TAI_KHOAN = P_MA_TAI_KHOAN;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20108, 'Khong tim thay tai khoan can khoa.');
    END IF;

    INSERT INTO NHAT_KY_HE_THONG VALUES (
        FN_NEXT_ID('NK', SEQ_NK.NEXTVAL),
        P_NGUOI_THUC_HIEN,
        N'Khóa tài khoản',
        SYSDATE,
        P_LY_DO
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_KHOA_TAI_KHOAN_START;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_CAP_NHAT_THAM_SO (
    P_MA_THAM_SO VARCHAR2,
    P_TEN_THAM_SO NVARCHAR2,
    P_GIA_TRI NVARCHAR2
)
IS
BEGIN
    SAVEPOINT SP_CAP_NHAT_THAM_SO_START;

    MERGE INTO THAM_SO TS
    USING (
        SELECT P_MA_THAM_SO MA_THAM_SO, P_TEN_THAM_SO TEN_THAM_SO, P_GIA_TRI GIA_TRI
        FROM DUAL
    ) S
    ON (TS.MA_THAM_SO = S.MA_THAM_SO)
    WHEN MATCHED THEN
        UPDATE SET TS.TEN_THAM_SO = S.TEN_THAM_SO,
                   TS.GIA_TRI = S.GIA_TRI,
                   TS.NGAY_CAP_NHAT = SYSDATE
    WHEN NOT MATCHED THEN
        INSERT (MA_THAM_SO, TEN_THAM_SO, GIA_TRI, NGAY_CAP_NHAT)
        VALUES (S.MA_THAM_SO, S.TEN_THAM_SO, S.GIA_TRI, SYSDATE);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_CAP_NHAT_THAM_SO_START;
        RAISE;
END;
/
