-- ============================================================
-- 06_VIEWS_FOR_JAVA.sql
-- View dong bo schema chi tiet voi DatabaseDataLoader JavaFX.
-- VAN_HANH va NOI_DUNG la bang tuong thich de giao dien doc nhanh.
-- ============================================================

CREATE OR REPLACE VIEW HO_SO_TNV AS
SELECT
    TG.MA_TAI_KHOAN,
    HS.MA_HO_SO,
    HS.HO_TEN,
    HS.MSSV,
    HS.SO_DIEN_THOAI,
    HS.KHOA,
    HS.TRUONG,
    TG.MA_CHIEN_DICH,
    TG.TRANG_THAI_DUYET,
    TO_CHAR(TG.DIEM_DANH_GIA) AS DIEM_DANH_GIA
FROM THAM_GIA_TNV TG
JOIN HO_SO_SINH_VIEN HS ON HS.MA_TAI_KHOAN = TG.MA_TAI_KHOAN;

CREATE OR REPLACE VIEW DOI_TAC_TAI_TRO AS
SELECT
    DT.MA_DOI_TAC,
    DT.TEN_DOI_TAC,
    DT.LINH_VUC,
    DT.SO_DIEN_THOAI,
    DT.EMAIL,
    DT.DIA_CHI,
    TT.MA_CHIEN_DICH,
    TT.GIA_TRI_TAI_TRO,
    TO_CHAR(TT.NGAY_KY_KET, 'DD/MM/YYYY') AS NGAY_KY_KET
FROM DOI_TAC DT
JOIN TAI_TRO TT ON TT.MA_DOI_TAC = DT.MA_DOI_TAC;

CREATE OR REPLACE VIEW QUYEN_GOP AS
SELECT
    QG.MA_QUYEN_GOP,
    QG.NGUOI_QUYEN_GOP,
    QG.MA_CHIEN_DICH,
    TO_CHAR(QG.NGAY_GIAO_DICH, 'DD/MM/YYYY') AS NGAY_QUYEN_GOP,
    TO_CHAR(QG.PHUONG_THUC) AS HINH_THUC,
    'Quyên góp tiền cho chiến dịch' AS NOI_DUNG_QUYEN_GOP,
    QG.SO_TIEN
FROM QUYEN_GOP_TIEN QG
UNION ALL
SELECT
    P.MA_PHIEU_QG AS MA_QUYEN_GOP,
    P.NGUOI_QUYEN_GOP,
    P.MA_CHIEN_DICH,
    TO_CHAR(P.NGAY_TIEP_NHAN, 'DD/MM/YYYY') AS NGAY_QUYEN_GOP,
    'Vật phẩm' AS HINH_THUC,
    LISTAGG(TO_CHAR(L.TEN_LOAI) || ': ' || CT.SO_LUONG || ' ' || TO_CHAR(L.DON_VI_TINH), '; ')
        WITHIN GROUP (ORDER BY L.TEN_LOAI) AS NOI_DUNG_QUYEN_GOP,
    0 AS SO_TIEN
FROM PHIEU_QUYEN_GOP_VP P
JOIN CHI_TIET_QUYEN_GOP_VP CT ON CT.MA_PHIEU_QG = P.MA_PHIEU_QG
JOIN LOAI_VAT_PHAM L ON L.MA_LOAI = CT.MA_LOAI
GROUP BY P.MA_PHIEU_QG, P.NGUOI_QUYEN_GOP, P.MA_CHIEN_DICH, P.NGAY_TIEP_NHAN;

CREATE OR REPLACE VIEW BAO_CAO_CHIEN_DICH AS
SELECT
    CD.MA_CHIEN_DICH,
    CD.TEN_CHIEN_DICH,
    CD.MUC_TIEU_TIEN,
    FN_TONG_QUYEN_GOP_TIEN(CD.MA_CHIEN_DICH) AS TONG_QUYEN_GOP_TIEN,
    FN_TONG_TAI_TRO(CD.MA_CHIEN_DICH) AS TONG_TAI_TRO,
    FN_TONG_CHI_TIEU(CD.MA_CHIEN_DICH) AS TONG_CHI_TIEU,
    FN_SO_TNV_CHIEN_DICH(CD.MA_CHIEN_DICH) AS SO_TNV,
    FN_SO_TNV_DA_DUYET(CD.MA_CHIEN_DICH) AS SO_TNV_DA_DUYET,
    FN_TY_LE_DAT_MUC_TIEU(CD.MA_CHIEN_DICH) AS TY_LE_DAT_MUC_TIEU,
    FN_TRANG_THAI_TONG_HOP_CD(CD.MA_CHIEN_DICH) AS TRANG_THAI_TONG_HOP
FROM CHIEN_DICH CD;
