-- ============================================================
-- 07_FIX_VIETNAMESE_ENCODING.sql
-- Fix Vietnamese text that was inserted through a mismatched
-- SQLPlus/client encoding. The data was UTF-8 bytes interpreted
-- as Windows-1252, so Oracle stores broken Vietnamese labels.
-- This script repairs only columns whose ASCIISTR form contains
-- mojibake markers, so it is safe to run after seed data.
-- ============================================================

SET DEFINE OFF
SET SERVEROUTPUT ON

DECLARE
    PROCEDURE DROP_CONSTRAINT_IF_EXISTS(P_TABLE_NAME VARCHAR2, P_CONSTRAINT_NAME VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE ' || P_TABLE_NAME || ' DROP CONSTRAINT ' || P_CONSTRAINT_NAME;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2443 THEN
                RAISE;
            END IF;
    END;
BEGIN
    DROP_CONSTRAINT_IF_EXISTS('BINH_LUAN', 'CK_BL_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('CHIEN_DICH', 'CK_CD_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('CHI_TIEU', 'CK_CT_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('CONG_VIEC', 'CK_CV_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('DIEM_DANH', 'CK_DD_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('DUYET_CHIEN_DICH', 'CK_DCD_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('GIAY_CHUNG_NHAN', 'CK_GCN_XEP_LOAI');
    DROP_CONSTRAINT_IF_EXISTS('MINH_CHUNG_TNV', 'CK_MCTNV_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('PHAN_CONG', 'CK_PC_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('PHIEU_QUYEN_GOP_VP', 'CK_PQGVP_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('PHIEU_XUAT_VAT_PHAM', 'CK_PXVP_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('QUYEN_GOP_TIEN', 'CK_QGT_PHUONG_THUC');
    DROP_CONSTRAINT_IF_EXISTS('QUYEN_GOP_TIEN', 'CK_QGT_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('TAI_TRO', 'CK_TTRO_HINH_THUC');
    DROP_CONSTRAINT_IF_EXISTS('TAI_TRO', 'CK_TTRO_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('THAM_GIA_TNV', 'CK_TG_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('THANH_TOAN', 'CK_THANH_TOAN_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('THONG_BAO', 'CK_TB_TRANG_THAI');
    DROP_CONSTRAINT_IF_EXISTS('TIN_TUC', 'CK_TT_TRANG_THAI');
END;
/

BEGIN
    FOR T IN (SELECT TRIGGER_NAME FROM USER_TRIGGERS) LOOP
        EXECUTE IMMEDIATE 'ALTER TRIGGER ' || DBMS_ASSERT.SIMPLE_SQL_NAME(T.TRIGGER_NAME) || ' DISABLE';
    END LOOP;
END;
/

DECLARE
    V_SQL   VARCHAR2(4000);
    V_ROWS  NUMBER;
BEGIN
    FOR C IN (
        SELECT T.TABLE_NAME, C.COLUMN_NAME
        FROM USER_TABLES T
        JOIN USER_TAB_COLUMNS C
            ON C.TABLE_NAME = T.TABLE_NAME
        WHERE C.DATA_TYPE IN ('VARCHAR2', 'CHAR', 'NVARCHAR2', 'NCHAR')
        ORDER BY T.TABLE_NAME, C.COLUMN_ID
    ) LOOP
        V_SQL :=
            'UPDATE ' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.TABLE_NAME)
            || ' SET ' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME)
            || ' = UTL_I18N.RAW_TO_CHAR(UTL_I18N.STRING_TO_RAW('
            || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME)
            || ', ''WE8MSWIN1252''), ''AL32UTF8'')'
            || ' WHERE ' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || ' IS NOT NULL'
            || ' AND ('
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\00C2'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\00C3'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\00C4'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\00C5'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\00C6'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\00E1\00'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\008'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\009'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\2018'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\2019'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\2021'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\2039'') > 0 OR '
            || 'INSTR(ASCIISTR(' || DBMS_ASSERT.SIMPLE_SQL_NAME(C.COLUMN_NAME) || '), ''\203A'') > 0'
            || ')';

        BEGIN
            EXECUTE IMMEDIATE V_SQL;
            V_ROWS := SQL%ROWCOUNT;
            IF V_ROWS > 0 THEN
                DBMS_OUTPUT.PUT_LINE(C.TABLE_NAME || '.' || C.COLUMN_NAME || ': ' || V_ROWS || ' row(s) repaired');
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Skipped ' || C.TABLE_NAME || '.' || C.COLUMN_NAME || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/

ALTER TABLE BINH_LUAN ADD CONSTRAINT CK_BL_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('Hi\1EC3n th\1ECB'), UNISTR('\1EA8n')));

ALTER TABLE CHIEN_DICH ADD CONSTRAINT CK_CD_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110ang x\00E9t'), UNISTR('\0110\00E3 duy\1EC7t'), UNISTR('\0110ang th\1EF1c hi\1EC7n'), UNISTR('Ho\00E0n th\00E0nh'), UNISTR('T\1EA1m d\1EEBng'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE CHI_TIEU ADD CONSTRAINT CK_CT_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110\00E3 duy\1EC7t'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE CONG_VIEC ADD CONSTRAINT CK_CV_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('\0110ang ph\00E2n c\00F4ng'), UNISTR('\0110\00E3 ph\00E2n c\00F4ng'), UNISTR('Ho\00E0n th\00E0nh'), UNISTR('T\1EA1m d\1EEBng')));

ALTER TABLE DIEM_DANH ADD CONSTRAINT CK_DD_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD x\00E1c nh\1EADn'), UNISTR('C\00F3 m\1EB7t'), UNISTR('V\1EAFng m\1EB7t'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE DUYET_CHIEN_DICH ADD CONSTRAINT CK_DCD_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110ang x\00E9t'), UNISTR('\0110\00E3 duy\1EC7t'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE GIAY_CHUNG_NHAN ADD CONSTRAINT CK_GCN_XEP_LOAI
    CHECK (XEP_LOAI IN (UNISTR('Xu\1EA5t s\1EAFc'), UNISTR('T\1ED1t'), UNISTR('Kh\00E1'), UNISTR('\0110\1EA1t')));

ALTER TABLE MINH_CHUNG_TNV ADD CONSTRAINT CK_MCTNV_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD x\00E1c nh\1EADn'), UNISTR('\0110\00E3 x\00E1c nh\1EADn'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE PHAN_CONG ADD CONSTRAINT CK_PC_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('\0110\00E3 ph\00E2n c\00F4ng'), UNISTR('\0110ang th\1EF1c hi\1EC7n'), UNISTR('Ho\00E0n th\00E0nh'), UNISTR('H\1EE7y')));

ALTER TABLE PHIEU_QUYEN_GOP_VP ADD CONSTRAINT CK_PQGVP_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD x\00E1c nh\1EADn'), UNISTR('\0110\00E3 x\00E1c nh\1EADn'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE PHIEU_XUAT_VAT_PHAM ADD CONSTRAINT CK_PXVP_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110\00E3 xu\1EA5t'), UNISTR('H\1EE7y')));

ALTER TABLE QUYEN_GOP_TIEN ADD CONSTRAINT CK_QGT_PHUONG_THUC
    CHECK (PHUONG_THUC IN (UNISTR('Ti\1EC1n m\1EB7t'), UNISTR('Chuy\1EC3n kho\1EA3n')));

ALTER TABLE QUYEN_GOP_TIEN ADD CONSTRAINT CK_QGT_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD x\00E1c nh\1EADn'), UNISTR('\0110\00E3 x\00E1c nh\1EADn'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE TAI_TRO ADD CONSTRAINT CK_TTRO_HINH_THUC
    CHECK (HINH_THUC IN (UNISTR('Ti\1EC1n m\1EB7t'), UNISTR('Chuy\1EC3n kho\1EA3n'), UNISTR('V\1EADt ph\1EA9m'), UNISTR('V\1EADt t\01B0'), UNISTR('D\1ECBch v\1EE5')));

ALTER TABLE TAI_TRO ADD CONSTRAINT CK_TTRO_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD x\00E1c nh\1EADn'), UNISTR('\0110\00E3 x\00E1c nh\1EADn'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE THAM_GIA_TNV ADD CONSTRAINT CK_TG_TRANG_THAI
    CHECK (TRANG_THAI_DUYET IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110ang x\00E9t'), UNISTR('\0110\00E3 duy\1EC7t'), UNISTR('T\1EEB ch\1ED1i')));

ALTER TABLE THANH_TOAN ADD CONSTRAINT CK_THANH_TOAN_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\1EDD x\00E1c nh\1EADn'), UNISTR('\0110\00E3 thanh to\00E1n'), UNISTR('Th\1EA5t b\1EA1i'), UNISTR('Ho\00E0n ti\1EC1n')));

ALTER TABLE THONG_BAO ADD CONSTRAINT CK_TB_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Ch\01B0a \0111\1ECDc'), UNISTR('\0110\00E3 \0111\1ECDc'), UNISTR('\1EA8n')));

ALTER TABLE TIN_TUC ADD CONSTRAINT CK_TT_TRANG_THAI
    CHECK (TRANG_THAI IN (UNISTR('Nh\00E1p'), UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110\00E3 \0111\0103ng'), UNISTR('\1EA8n')));

BEGIN
    FOR T IN (SELECT TRIGGER_NAME FROM USER_TRIGGERS) LOOP
        EXECUTE IMMEDIATE 'ALTER TRIGGER ' || DBMS_ASSERT.SIMPLE_SQL_NAME(T.TRIGGER_NAME) || ' ENABLE';
    END LOOP;
END;
/

COMMIT;
