-- ============================================================
-- 08_RECREATE_REPORT_FUNCTIONS.sql
-- Recreate report functions with UNISTR literals so report totals
-- keep working after Vietnamese data is normalized.
-- ============================================================

SET DEFINE OFF

CREATE OR REPLACE FUNCTION FN_TONG_QUYEN_GOP_TIEN(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN), 0)
    INTO V_TOTAL
    FROM QUYEN_GOP_TIEN
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI = UNISTR('\0110\00E3 x\00E1c nh\1EADn');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_TAI_TRO(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(GIA_TRI_TAI_TRO), 0)
    INTO V_TOTAL
    FROM TAI_TRO
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI = UNISTR('\0110\00E3 x\00E1c nh\1EADn');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_CHI_TIEU(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN_CHI), 0)
    INTO V_TOTAL
    FROM CHI_TIEU
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI = UNISTR('\0110\00E3 duy\1EC7t');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_NGUON_LUC_CHIEN_DICH(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
BEGIN
    RETURN FN_TONG_QUYEN_GOP_TIEN(P_MA_CHIEN_DICH) + FN_TONG_TAI_TRO(P_MA_CHIEN_DICH);
END;
/

CREATE OR REPLACE FUNCTION FN_SO_TNV_DA_DUYET(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM THAM_GIA_TNV
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND TRANG_THAI_DUYET = UNISTR('\0110\00E3 duy\1EC7t');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_GIO_TNV(
    P_MA_TAI_KHOAN VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(DD.SO_GIO_GHI_NHAN), 0)
    INTO V_TOTAL
    FROM DIEM_DANH DD
    JOIN THAM_GIA_TNV TG ON TG.MA_THAM_GIA = DD.MA_THAM_GIA
    WHERE TG.MA_TAI_KHOAN = P_MA_TAI_KHOAN
      AND DD.TRANG_THAI = UNISTR('C\00F3 m\1EB7t');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TONG_VAT_PHAM_QUYEN_GOP(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(CT.SO_LUONG), 0)
    INTO V_TOTAL
    FROM PHIEU_QUYEN_GOP_VP P
    JOIN CHI_TIET_QUYEN_GOP_VP CT ON CT.MA_PHIEU_QG = P.MA_PHIEU_QG
    WHERE P.MA_CHIEN_DICH = P_MA_CHIEN_DICH
      AND P.TRANG_THAI = UNISTR('\0110\00E3 x\00E1c nh\1EADn');

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TY_LE_DAT_MUC_TIEU(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NUMBER
IS
    V_GOAL NUMBER;
BEGIN
    SELECT NVL(MUC_TIEU_TIEN, 0)
    INTO V_GOAL
    FROM CHIEN_DICH
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    IF V_GOAL <= 0 THEN
        RETURN 0;
    END IF;

    RETURN ROUND(FN_TONG_NGUON_LUC_CHIEN_DICH(P_MA_CHIEN_DICH) / V_GOAL * 100, 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_VAN_HANH_CHO_XU_LY
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM (
        SELECT TRANG_THAI FROM DUYET_CHIEN_DICH
        UNION ALL SELECT TRANG_THAI_DUYET AS TRANG_THAI FROM THAM_GIA_TNV
        UNION ALL SELECT TRANG_THAI FROM CONG_VIEC
        UNION ALL SELECT TRANG_THAI FROM DIEM_DANH
        UNION ALL SELECT TRANG_THAI FROM CHI_TIEU
        UNION ALL SELECT TRANG_THAI FROM QUYEN_GOP_TIEN
        UNION ALL SELECT TRANG_THAI FROM PHIEU_QUYEN_GOP_VP
        UNION ALL SELECT TRANG_THAI FROM MINH_CHUNG_TNV
    )
    WHERE TRANG_THAI IN (
        UNISTR('Ch\1EDD duy\1EC7t'),
        UNISTR('\0110ang x\00E9t'),
        UNISTR('\0110ang ph\00E2n c\00F4ng'),
        UNISTR('Ch\1EDD x\00E1c nh\1EADn')
    );

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_NOI_DUNG_CAN_DUYET
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM (
        SELECT TRANG_THAI FROM TIN_TUC
        UNION ALL SELECT TRANG_THAI FROM BINH_LUAN
    )
    WHERE TRANG_THAI IN (UNISTR('Nh\00E1p'), UNISTR('Ch\1EDD duy\1EC7t'));

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_TRANG_THAI_TONG_HOP_CD(
    P_MA_CHIEN_DICH VARCHAR2
) RETURN NVARCHAR2
IS
    V_STATUS NVARCHAR2(50);
    V_PERCENT NUMBER;
BEGIN
    SELECT TRANG_THAI
    INTO V_STATUS
    FROM CHIEN_DICH
    WHERE MA_CHIEN_DICH = P_MA_CHIEN_DICH;

    V_PERCENT := FN_TY_LE_DAT_MUC_TIEU(P_MA_CHIEN_DICH);

    IF V_STATUS = UNISTR('Ho\00E0n th\00E0nh') OR V_PERCENT >= 100 THEN
        RETURN UNISTR('\0110\1EA1t m\1EE5c ti\00EAu');
    ELSIF V_STATUS = UNISTR('\0110ang th\1EF1c hi\1EC7n') THEN
        RETURN UNISTR('\0110ang v\1EADn \0111\1ED9ng');
    ELSIF V_STATUS IN (UNISTR('Ch\1EDD duy\1EC7t'), UNISTR('\0110ang x\00E9t')) THEN
        RETURN UNISTR('Ch\1EDD qu\1EA3n l\00FD x\1EED l\00FD');
    ELSE
        RETURN V_STATUS;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN UNISTR('Kh\00F4ng t\1ED3n t\1EA1i');
END;
/

COMMIT;
