-- ============================================================
-- oracle_preview.sql
-- Xem nhanh database CHARITY sau khi chay oracle_setup.sql.
-- ============================================================

SET PAGESIZE 300
SET LINESIZE 240
COLUMN TABLE_NAME FORMAT A32
COLUMN OBJECT_TYPE FORMAT A16
COLUMN OBJECT_NAME FORMAT A40
COLUMN STATUS FORMAT A10
COLUMN TEN_DANG_NHAP FORMAT A14
COLUMN VAI_TRO FORMAT A12
COLUMN HO_TEN_HIEN_THI FORMAT A28
COLUMN MA_CHIEN_DICH FORMAT A14
COLUMN TEN_CHIEN_DICH FORMAT A36
COLUMN TRANG_THAI FORMAT A22
COLUMN TEN_DOI_TAC FORMAT A24
COLUMN NGUOI_QUYEN_GOP FORMAT A24
COLUMN HINH_THUC FORMAT A18

PROMPT ===== TABLES =====
SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;

PROMPT ===== ROW COUNTS =====
SELECT 'TAI_KHOAN' AS TABLE_NAME, COUNT(*) AS ROWS_COUNT FROM TAI_KHOAN
UNION ALL SELECT 'HO_SO_SINH_VIEN', COUNT(*) FROM HO_SO_SINH_VIEN
UNION ALL SELECT 'CHIEN_DICH', COUNT(*) FROM CHIEN_DICH
UNION ALL SELECT 'THAM_GIA_TNV', COUNT(*) FROM THAM_GIA_TNV
UNION ALL SELECT 'CONG_VIEC', COUNT(*) FROM CONG_VIEC
UNION ALL SELECT 'PHAN_CONG', COUNT(*) FROM PHAN_CONG
UNION ALL SELECT 'DIEM_DANH', COUNT(*) FROM DIEM_DANH
UNION ALL SELECT 'DOI_TAC', COUNT(*) FROM DOI_TAC
UNION ALL SELECT 'TAI_TRO', COUNT(*) FROM TAI_TRO
UNION ALL SELECT 'QUYEN_GOP_TIEN', COUNT(*) FROM QUYEN_GOP_TIEN
UNION ALL SELECT 'PHIEU_QUYEN_GOP_VP', COUNT(*) FROM PHIEU_QUYEN_GOP_VP
UNION ALL SELECT 'CHI_TIET_QUYEN_GOP_VP', COUNT(*) FROM CHI_TIET_QUYEN_GOP_VP
UNION ALL SELECT 'LOAI_VAT_PHAM', COUNT(*) FROM LOAI_VAT_PHAM
UNION ALL SELECT 'PHIEU_XUAT_VAT_PHAM', COUNT(*) FROM PHIEU_XUAT_VAT_PHAM
UNION ALL SELECT 'CHI_TIEU', COUNT(*) FROM CHI_TIEU
UNION ALL SELECT 'TIN_TUC', COUNT(*) FROM TIN_TUC
UNION ALL SELECT 'BINH_LUAN', COUNT(*) FROM BINH_LUAN
UNION ALL SELECT 'THONG_BAO', COUNT(*) FROM THONG_BAO
UNION ALL SELECT 'NHAT_KY_HE_THONG', COUNT(*) FROM NHAT_KY_HE_THONG;

PROMPT ===== BUSINESS OBJECTS =====
SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('TRIGGER', 'PROCEDURE', 'FUNCTION', 'SEQUENCE', 'VIEW')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT ===== SAMPLE ACCOUNTS =====
SELECT TEN_DANG_NHAP, VAI_TRO, HO_TEN_HIEN_THI, MA_LIEN_KET
FROM TAI_KHOAN
ORDER BY TEN_DANG_NHAP
FETCH FIRST 12 ROWS ONLY;

PROMPT ===== SAMPLE CAMPAIGN REPORT =====
SELECT MA_CHIEN_DICH, TEN_CHIEN_DICH, MUC_TIEU_TIEN, TONG_QUYEN_GOP_TIEN,
       TONG_TAI_TRO, TONG_CHI_TIEU, SO_TNV, TY_LE_DAT_MUC_TIEU, TRANG_THAI_TONG_HOP
FROM BAO_CAO_CHIEN_DICH
ORDER BY MA_CHIEN_DICH;

PROMPT ===== SAMPLE VOLUNTEERS VIEW FOR JAVA =====
SELECT MA_TAI_KHOAN, HO_TEN, MSSV, SO_DIEN_THOAI, TRUONG, MA_CHIEN_DICH, TRANG_THAI_DUYET
FROM HO_SO_TNV
ORDER BY MA_TAI_KHOAN, MA_CHIEN_DICH
FETCH FIRST 12 ROWS ONLY;

PROMPT ===== SAMPLE SPONSORS VIEW FOR JAVA =====
SELECT MA_DOI_TAC, TEN_DOI_TAC, SO_DIEN_THOAI, EMAIL, MA_CHIEN_DICH, GIA_TRI_TAI_TRO
FROM DOI_TAC_TAI_TRO
ORDER BY MA_DOI_TAC, MA_CHIEN_DICH
FETCH FIRST 12 ROWS ONLY;

PROMPT ===== SAMPLE DONATIONS VIEW FOR JAVA =====
SELECT MA_QUYEN_GOP, NGUOI_QUYEN_GOP, MA_CHIEN_DICH, HINH_THUC, SO_TIEN
FROM QUYEN_GOP
ORDER BY MA_QUYEN_GOP
FETCH FIRST 12 ROWS ONLY;

PROMPT ===== INVENTORY =====
SELECT MA_LOAI, TEN_LOAI, DON_VI_TINH, SO_LUONG_TON
FROM LOAI_VAT_PHAM
ORDER BY MA_LOAI;

EXIT
