SET PAGESIZE 200
SET LINESIZE 220
COLUMN OBJECT_TYPE FORMAT A16
COLUMN OBJECT_NAME FORMAT A40
COLUMN STATUS FORMAT A10

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('TRIGGER', 'PROCEDURE', 'FUNCTION', 'SEQUENCE', 'VIEW')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

EXIT
